name: ecir2026
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.4.26=py311h06a4308_0
  - cpuonly=2.0=0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py311h06a4308_0
  - numpy-base=2.0.1=py311hf175353_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.16=h5eee18b_0
  - pip=23.3.1=py311h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.11=he870216_0
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.2=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - setuptools=78.1.1=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py311h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h993c535_1
  - typing_extensions=4.12.2=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.7
      - aiosignal==1.3.2
      - airportsdata==20250523
      - alembic==1.16.1
      - annotated-types==0.7.0
      - anyio==4.9.0
      - arxiv==2.1.3
      - astor==0.8.1
      - asyncer==0.0.8
      - attrs==25.3.0
      - backoff==2.2.1
      - beautifulsoup4==4.13.3
      - blake3==1.0.5
      - blinker==1.9.0
      - brotli==1.1.0
      - cachetools==6.0.0
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - compressed-tensors==0.9.4
      - contourpy==1.3.2
      - cryptography==45.0.3
      - cssselect2==0.8.0
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - cython==3.1.1
      - dataclasses-json==0.6.7
      - datasets==3.6.0
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - docopt==0.6.2
      - dspy==2.6.27
      - einops==0.8.1
      - email-validator==2.2.0
      - emoji==2.14.1
      - eval-type-backport==0.2.2
      - fastapi==0.115.10
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - feedparser==6.0.11
      - filelock==3.18.0
      - filetype==1.2.0
      - flask==3.1.1
      - flatbuffers==25.2.10
      - fonttools==4.58.1
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - gguf==0.17.0
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.2
      - grpcio==1.72.1
      - h11==0.16.0
      - hf-xet==1.1.2
      - html5lib==1.1
      - htmldocx==0.0.6
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.33.0
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - inquirerpy==0.3.4
      - interegular==0.3.3
      - ir-measures==0.3.7
      - itsdangerous==2.2.0
      - jiter==0.10.0
      - joblib==1.5.1
      - json-repair==0.39.1
      - json5==0.10.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - langchain==0.3.19
      - langchain-community==0.3.18
      - langchain-core==0.3.40
      - langchain-ollama==0.2.3
      - langchain-openai==0.3.7
      - langchain-text-splitters==0.3.6
      - langchain-together==0.3.0
      - langdetect==1.0.9
      - langgraph==0.3.2
      - langgraph-checkpoint==2.0.16
      - langgraph-cli==0.1.74
      - langgraph-prebuilt==0.1.1
      - langgraph-sdk==0.1.53
      - langsmith==0.3.43
      - lark==1.2.2
      - litellm==1.72.0
      - llguidance==0.7.27
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - loguru==0.7.3
      - lxml==5.4.0
      - lxml-html-clean==0.4.1
      - magicattr==0.1.6
      - mako==1.3.10
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markdown2==2.5.3
      - marshmallow==3.26.1
      - matplotlib==3.10.3
      - md2pdf==1.0.1
      - mdurl==0.1.2
      - mistral-common==1.5.6
      - mistune==3.1.2
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - olefile==0.47
      - ollama==0.5.1
      - onnxruntime==1.22.0
      - openai==1.83.0
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.34.0
      - opentelemetry-exporter-otlp==1.34.0
      - opentelemetry-exporter-otlp-proto-common==1.34.0
      - opentelemetry-exporter-otlp-proto-grpc==1.34.0
      - opentelemetry-exporter-otlp-proto-http==1.34.0
      - opentelemetry-proto==1.34.0
      - opentelemetry-sdk==1.34.0
      - opentelemetry-semantic-conventions==0.55b0
      - opentelemetry-semantic-conventions-ai==0.4.9
      - optuna==4.3.0
      - orjson==3.10.18
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==24.2
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post5
      - pfzy==0.3.4
      - pillow==11.2.1
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - protobuf==5.29.5
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.8.1
      - pydyf==0.11.0
      - pygments==2.19.1
      - pyjnius==1.6.1
      - pymupdf==1.25.3
      - pyndeval==0.0.6
      - pyparsing==3.2.3
      - pypdf==5.6.0
      - pyphen==0.17.2
      - pyserini==1.0.0
      - python-dateutil==2.9.0.post0
      - python-docx==1.1.2
      - python-dotenv==1.0.1
      - python-iso639==2025.2.18
      - python-json-logger==3.3.0
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - python-oxmsg==0.0.2
      - pytrec-eval-terrier==0.5.7
      - pytz==2025.2
      - pyzmq==26.4.0
      - rapidfuzz==3.13.0
      - ray==2.46.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - rich-toolkit==0.14.7
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - sgmllib3k==1.0.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - sqlalchemy==2.0.41
      - starlette==0.46.2
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - tinyhtml5==2.0.0
      - tokenizers==0.21.1
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.52.4
      - triton==3.3.0
      - typer==0.16.0
      - typing-extensions==4.14.0
      - typing-inspect==0.9.0
      - tzdata==2025.2
      - ujson==5.10.0
      - unstructured==0.16.23
      - unstructured-client==0.30.6
      - urllib3==2.4.0
      - uv==0.8.4
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - vllm==0.9.0.1
      - watchfiles==1.0.5
      - wcwidth==0.2.13
      - weasyprint==65.1
      - webencodings==0.5.1
      - websockets==15.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.30
      - xgrammar==0.1.19
      - xxhash==3.5.0
      - yarl==1.20.0
      - zipp==3.22.0
      - zopfli==0.2.3.post1
      - zstandard==0.23.0
prefix: /home/hltcoe/flandry/.conda/envs/scale25gptr
